version: 2.1
defaults: &defaults
  docker:
    - image: lingjun/sfdx:latest

jobs:
  setup_dx:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Decrypet Server Key
          command: |
            openssl enc -aes-256-cbc -md sha256 -salt -d -in assets/server.key.enc -out assets/server.key -k $SERVER_KEY_PASSWORD -pbkdf2
      - persist_to_workspace:
          root: ~/
          paths:
            - .sfdx/*
            - project/*
  QA Deployment:
    <<: *defaults
    steps: # steps that comprise the `build` job
      - attach_workspace:
          at: ~/
      - run:
          name: "Verity in scratch org"
          command: |
            sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile $PWD/assets/server.key --username $SF_USERNAME --setdefaultdevhubusername -a HubOrg
            # Create scratch org
            # sfdx force:org:create --setdefaultusername --definitionfile config/project-scratch-def.json --wait 10 --durationdays 1
            # Display scratch org details
            # sfdx force:org:display
            # Push source to scratch org (this is with source code, all files, etc)
            # sfdx force:source:push
            # Assign DreamHouse permission set to scratch org default user
            # sfdx force:user:permset:assign --permsetname DreamHouse
            # Add sample data into app
            # sfdx force:data:tree:import --plan data/sample-data-plan.json
            # Unit Testing
            # sfdx force:apex:test:run --wait 10 --resultformat human --codecoverage --testlevel RunLocalTests
      - run:
          name: "Cleanup Scratch Org"
          command: |
            # Delete Scratch Org
            echo "delete the scratch org"
            # sfdx force:org:delete --noprompt
          when: always

  SIT Deployment:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Authorize to DevHub"
          command: |
            # Authenticate to the Dev Hub using the server key
            sfdx force:auth:jwt:grant --setdefaultdevhubusername --clientid $SF_CONSUMER_KEY --jwtkeyfile assets/server.key --username $SF_USERNAME
      - run:
          name: "Create scratch org"
          command: |
            # Create scratch org
            # sfdx force:org:create --setdefaultusername --definitionfile config/project-scratch-def.json --wait 10 --durationdays 1
            
            sfdx force:org:display
      - run:
          name: "Display package version"
          command: |
            # Increment package version number
            echo $PACKAGE_NAME
            PACKAGE_VERSION_JSON="$(eval sfdx force:package:version:list --concise --released --packages $PACKAGE_NAME --json | jq '.result | sort_by(-.MajorVersion, -.MinorVersion, -.PatchVersion, -.BuildNumber) | .[0] // ""')"
            echo $PACKAGE_VERSION_JSON | jq .
      - run:
          name: "Increase package version"
          command: |
            IS_RELEASED=$(echo $PACKAGE_VERSION_JSON | jq -r '.IsReleased?')
            MAJOR_VERSION=$(echo $PACKAGE_VERSION_JSON | jq -r '.MajorVersion?')
            MINOR_VERSION=$(echo $PACKAGE_VERSION_JSON | jq -r '.MinorVersion?')
            PATCH_VERSION=$(echo $PACKAGE_VERSION_JSON | jq -r '.PatchVersion?')
            BUILD_VERSION="NEXT"
            if [ -z $MAJOR_VERSION ]; then MAJOR_VERSION=1; fi;
            if [ -z $MINOR_VERSION ]; then MINOR_VERSION=0; fi;
            if [ -z $PATCH_VERSION ]; then PATCH_VERSION=0; fi;
            if [ "$IS_RELEASED" = "true" ]; then MINOR_VERSION=$(($MINOR_VERSION+1)); fi;
            VERSION_NUMBER="$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION.$BUILD_VERSION"
            echo $VERSION_NUMBER
            echo $PACKAGE_NAME
      - run:
          name: "Create new package"
          command: |
            # Create packaged version
            export PACKAGE_VERSION_ID="$(eval sfdx force:package:version:create --package $PACKAGE_NAME --versionnumber $VERSION_NUMBER --installationkeybypass --wait 10 --json | jq -r '.result.SubscriberPackageVersionId')"
            # Save your PACKAGE_VERSION_ID to a file for later use during deploy so you know what version to deploy
            echo "$PACKAGE_VERSION_ID" > PACKAGE_VERSION_ID.TXT
            echo $PACKAGE_VERSION_ID
            # Install package in DevHub org (this is a compiled library of the app)
            sfdx force:package:list
      - run:
          name: "Install package to scratch org"
          command: |
            sfdx force:package:install --package $PACKAGE_VERSION_ID --wait 10 --publishwait 10 --noprompt
            # Assign DreamHouse permission set to scratch org default user
            sfdx force:user:permset:assign --permsetname DreamHouse
            # Add sample data into app
            sfdx force:data:tree:import --plan data/sample-data-plan.json
            # Run unit tests in scratch org
            sfdx force:apex:test:run --wait 10 --resultformat human --codecoverage --testlevel RunLocalTests
      - run:
          name: "Cleanup Scratch Org"
          command: |
            # Delete Scratch Org
            echo "delete the scratch org"
            # sfdx force:org:delete --noprompt
          when: always

      - store_artifacts:
          path: PACKAGE_VERSION_ID.TXT

workflows:
  version: 2
  build:
    jobs:
      - setup_dx
      - QA Deployment:
          requires:
            - setup_dx
          filters:
            branches: 
              only: /develop.*/
      - SIT Deployment:
          requires:
            - setup_dx
          filters:
            branches: 
              only: /feature.*/
      - Staging Deployment:
          type: approval
          requires:
            - setup_dx
          filters:
            branches:
              only: /master/
      - Production Deployment:
          type: approval
          requires:
            - setup_dx
          filters:
            branches:
              only: /master/


  