version: 2.1
defaults: &defaults
  docker:
    - image: lingjun/sfdx:latest

jobs:
  setup_dx:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Decrypet Server Key
          command: |
            openssl enc -aes-256-cbc -md sha256 -salt -d -in assets/server.key.enc -out assets/server.key -k $SERVER_KEY_PASSWORD -pbkdf2
      - persist_to_workspace:
          root: ~/
          paths:
            - .sfdx/*
            - project/*
  QA:
    <<: *defaults
    steps: # steps that comprise the `build` job
      - attach_workspace:
          at: ~/
      - run:
          name: "verity in scratch org"
          command: |
            ls -al
            sfdx force:auth:jwt:grant --clientid $SF_CONSUMER_KEY --jwtkeyfile $PWD/assets/server.key --username $SF_USERNAME --setdefaultdevhubusername -a HubOrg
            # Create scratch org
            sfdx force:org:create --setdefaultusername --definitionfile config/project-scratch-def.json --wait 10 --durationdays 1
            # Display scratch org details
            sfdx force:org:display
            # Push source to scratch org (this is with source code, all files, etc)
            sfdx force:source:push
            # Assign DreamHouse permission set to scratch org default user
            sfdx force:user:permset:assign --permsetname DreamHouse
            # Add sample data into app
            sfdx force:data:tree:import --plan data/sample-data-plan.json
            # Unit Testing
            sfdx force:apex:test:run --wait 10 --resultformat human --codecoverage --testlevel RunLocalTests
            # Delete Scratch Org
            sfdx force:org:delete --noprompt
  Packaging:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "packaging"
          command: |
            # Authenticate to the Dev Hub using the server key
            sfdx force:auth:jwt:grant --setdefaultdevhubusername --clientid $SF_CONSUMER_KEY --jwtkeyfile assets/server.key --username $SF_USERNAME
workflows:
  version: 2
  build:
    jobs:
      - setup_dx
      - Packaging:
          requires:
            - setup_dx
          filters:
            branches: 
              only: /.*develop.*/

  